// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: submodule/order_service/basket_items.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BasketItem represents an item in a shopping basket.
type BasketItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BasketId                string                 `protobuf:"bytes,2,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
	ProductId               string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FlashSaleEventProductId string                 `protobuf:"bytes,4,opt,name=flash_sale_event_product_id,json=flashSaleEventProductId,proto3" json:"flash_sale_event_product_id,omitempty"`
	DiscountProductId       string                 `protobuf:"bytes,5,opt,name=discount_product_id,json=discountProductId,proto3" json:"discount_product_id,omitempty"`
	Quantity                int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice               float32                `protobuf:"fixed32,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice              float32                `protobuf:"fixed32,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	ProductType             string                 `protobuf:"bytes,9,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"` // Possible values: 'REGULAR', 'FLASH_SALE', 'DISCOUNT'
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BasketItem) Reset() {
	*x = BasketItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketItem) ProtoMessage() {}

func (x *BasketItem) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketItem.ProtoReflect.Descriptor instead.
func (*BasketItem) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{0}
}

func (x *BasketItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasketItem) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *BasketItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BasketItem) GetFlashSaleEventProductId() string {
	if x != nil {
		return x.FlashSaleEventProductId
	}
	return ""
}

func (x *BasketItem) GetDiscountProductId() string {
	if x != nil {
		return x.DiscountProductId
	}
	return ""
}

func (x *BasketItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BasketItem) GetUnitPrice() float32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *BasketItem) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BasketItem) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *BasketItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BasketItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateBasketItemRequest represents a request to create a new basket item.
type CreateBasketItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItem *BasketItem `protobuf:"bytes,1,opt,name=basket_item,json=basketItem,proto3" json:"basket_item,omitempty"`
}

func (x *CreateBasketItemRequest) Reset() {
	*x = CreateBasketItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketItemRequest) ProtoMessage() {}

func (x *CreateBasketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketItemRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketItemRequest) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBasketItemRequest) GetBasketItem() *BasketItem {
	if x != nil {
		return x.BasketItem
	}
	return nil
}

// CreateBasketItemResponse represents a response to a CreateBasketItemRequest.
type CreateBasketItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItem *BasketItem `protobuf:"bytes,1,opt,name=basket_item,json=basketItem,proto3" json:"basket_item,omitempty"`
}

func (x *CreateBasketItemResponse) Reset() {
	*x = CreateBasketItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketItemResponse) ProtoMessage() {}

func (x *CreateBasketItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketItemResponse.ProtoReflect.Descriptor instead.
func (*CreateBasketItemResponse) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBasketItemResponse) GetBasketItem() *BasketItem {
	if x != nil {
		return x.BasketItem
	}
	return nil
}

// GetBasketItemRequest represents a request to get a basket item by ID.
type GetBasketItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBasketItemRequest) Reset() {
	*x = GetBasketItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketItemRequest) ProtoMessage() {}

func (x *GetBasketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketItemRequest.ProtoReflect.Descriptor instead.
func (*GetBasketItemRequest) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{3}
}

func (x *GetBasketItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetBasketItemResponse represents a response to a GetBasketItemRequest.
type GetBasketItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItem *BasketItem `protobuf:"bytes,1,opt,name=basket_item,json=basketItem,proto3" json:"basket_item,omitempty"`
}

func (x *GetBasketItemResponse) Reset() {
	*x = GetBasketItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketItemResponse) ProtoMessage() {}

func (x *GetBasketItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketItemResponse.ProtoReflect.Descriptor instead.
func (*GetBasketItemResponse) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{4}
}

func (x *GetBasketItemResponse) GetBasketItem() *BasketItem {
	if x != nil {
		return x.BasketItem
	}
	return nil
}

// DeleteBasketItemRequest represents a request to delete a basket item by ID.
type DeleteBasketItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBasketItemRequest) Reset() {
	*x = DeleteBasketItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketItemRequest) ProtoMessage() {}

func (x *DeleteBasketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteBasketItemRequest) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBasketItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteBasketItemResponse represents a response to a DeleteBasketItemRequest.
type DeleteBasketItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Success message
}

func (x *DeleteBasketItemResponse) Reset() {
	*x = DeleteBasketItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketItemResponse) ProtoMessage() {}

func (x *DeleteBasketItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteBasketItemResponse) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBasketItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListBasketItemsRequest represents a request to list basket items.
type ListBasketItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit    int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BasketId string `protobuf:"bytes,3,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"` // Filter by basket_id
}

func (x *ListBasketItemsRequest) Reset() {
	*x = ListBasketItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBasketItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasketItemsRequest) ProtoMessage() {}

func (x *ListBasketItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasketItemsRequest.ProtoReflect.Descriptor instead.
func (*ListBasketItemsRequest) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{7}
}

func (x *ListBasketItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBasketItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBasketItemsRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

// ListBasketItemsResponse represents a response to a ListBasketItemsRequest.
type ListBasketItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItems []*BasketItem `protobuf:"bytes,1,rep,name=basket_items,json=basketItems,proto3" json:"basket_items,omitempty"`
	Total       int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListBasketItemsResponse) Reset() {
	*x = ListBasketItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_order_service_basket_items_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBasketItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasketItemsResponse) ProtoMessage() {}

func (x *ListBasketItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_order_service_basket_items_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasketItemsResponse.ProtoReflect.Descriptor instead.
func (*ListBasketItemsResponse) Descriptor() ([]byte, []int) {
	return file_submodule_order_service_basket_items_proto_rawDescGZIP(), []int{8}
}

func (x *ListBasketItemsResponse) GetBasketItems() []*BasketItem {
	if x != nil {
		return x.BasketItems
	}
	return nil
}

func (x *ListBasketItemsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_submodule_order_service_basket_items_proto protoreflect.FileDescriptor

var file_submodule_order_service_basket_items_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x03, 0x0a,
	0x0a, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x1b, 0x66, 0x6c, 0x61, 0x73, 0x68,
	0x5f, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x66, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x55, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x56, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x53, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5f, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0x9b, 0x03, 0x0a, 0x11, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x26, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x23, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x26, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x25, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submodule_order_service_basket_items_proto_rawDescOnce sync.Once
	file_submodule_order_service_basket_items_proto_rawDescData = file_submodule_order_service_basket_items_proto_rawDesc
)

func file_submodule_order_service_basket_items_proto_rawDescGZIP() []byte {
	file_submodule_order_service_basket_items_proto_rawDescOnce.Do(func() {
		file_submodule_order_service_basket_items_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_order_service_basket_items_proto_rawDescData)
	})
	return file_submodule_order_service_basket_items_proto_rawDescData
}

var file_submodule_order_service_basket_items_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_submodule_order_service_basket_items_proto_goTypes = []any{
	(*BasketItem)(nil),               // 0: order_service.BasketItem
	(*CreateBasketItemRequest)(nil),  // 1: order_service.CreateBasketItemRequest
	(*CreateBasketItemResponse)(nil), // 2: order_service.CreateBasketItemResponse
	(*GetBasketItemRequest)(nil),     // 3: order_service.GetBasketItemRequest
	(*GetBasketItemResponse)(nil),    // 4: order_service.GetBasketItemResponse
	(*DeleteBasketItemRequest)(nil),  // 5: order_service.DeleteBasketItemRequest
	(*DeleteBasketItemResponse)(nil), // 6: order_service.DeleteBasketItemResponse
	(*ListBasketItemsRequest)(nil),   // 7: order_service.ListBasketItemsRequest
	(*ListBasketItemsResponse)(nil),  // 8: order_service.ListBasketItemsResponse
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_submodule_order_service_basket_items_proto_depIdxs = []int32{
	9,  // 0: order_service.BasketItem.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: order_service.BasketItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: order_service.CreateBasketItemRequest.basket_item:type_name -> order_service.BasketItem
	0,  // 3: order_service.CreateBasketItemResponse.basket_item:type_name -> order_service.BasketItem
	0,  // 4: order_service.GetBasketItemResponse.basket_item:type_name -> order_service.BasketItem
	0,  // 5: order_service.ListBasketItemsResponse.basket_items:type_name -> order_service.BasketItem
	1,  // 6: order_service.BasketItemService.CreateBasketItem:input_type -> order_service.CreateBasketItemRequest
	3,  // 7: order_service.BasketItemService.GetBasketItem:input_type -> order_service.GetBasketItemRequest
	5,  // 8: order_service.BasketItemService.DeleteBasketItem:input_type -> order_service.DeleteBasketItemRequest
	7,  // 9: order_service.BasketItemService.ListBasketItems:input_type -> order_service.ListBasketItemsRequest
	2,  // 10: order_service.BasketItemService.CreateBasketItem:output_type -> order_service.CreateBasketItemResponse
	4,  // 11: order_service.BasketItemService.GetBasketItem:output_type -> order_service.GetBasketItemResponse
	6,  // 12: order_service.BasketItemService.DeleteBasketItem:output_type -> order_service.DeleteBasketItemResponse
	8,  // 13: order_service.BasketItemService.ListBasketItems:output_type -> order_service.ListBasketItemsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_submodule_order_service_basket_items_proto_init() }
func file_submodule_order_service_basket_items_proto_init() {
	if File_submodule_order_service_basket_items_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_submodule_order_service_basket_items_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BasketItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBasketItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBasketItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListBasketItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_order_service_basket_items_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListBasketItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_order_service_basket_items_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_order_service_basket_items_proto_goTypes,
		DependencyIndexes: file_submodule_order_service_basket_items_proto_depIdxs,
		MessageInfos:      file_submodule_order_service_basket_items_proto_msgTypes,
	}.Build()
	File_submodule_order_service_basket_items_proto = out.File
	file_submodule_order_service_basket_items_proto_rawDesc = nil
	file_submodule_order_service_basket_items_proto_goTypes = nil
	file_submodule_order_service_basket_items_proto_depIdxs = nil
}
